name: Crear Arquetipos Multi-Lenguaje

on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Lenguaje del proyecto (ej: java, dotnet, angular, react)'
        required: true
        type: string
      version:
        description: 'Versión del lenguaje (ej: 17, 21, 8, 18)'
        required: true
        type: string
jobs:
  crear-arquetipo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Checkoout completo del repositorio"
      - name: Setup y construccion base ${{ github.event.inputs.language }} ${{ github.event.inputs.version }}
        run: echo "Setup de ${{ github.event.inputs.language }} ${{ github.event.inputs.version }} "
      - name: Crea arquetipo
        run: echo "Basado en la tecnologia va a ejecutar el bash para la construccion ejem. ./scripts/scaffold-${{ github.event.inputs.language }}.sh"
      - name: Crear repositorio en GitHub
        run: echo "Crea repositorio "
      - name: Publicar repositorio
        run: echo "Publica repositorio"
      - name: Envia informacion a Port
        run: echo "Envia estado de la publicacion, url del repositorio y ramas creadas"
